### PR TITLE
:children_crossing: add onboarding sequence on first use

### PR DESCRIPTION
**Pull request by anuejn**

### CODE REVIEW

**Comment by anuejn** [comment]
I think I need some input on the actual process

**Comment by anuejn** [comment]
@pajowu says:
* it would be nice to click through / perform the actions imitiately
* It shouldnt break if you already have models
* clicking outside shouldnt pause the flow
* no red things

**Comment by pajowu** [comment]
and a back-button to repeat a single step would be nice

**Comment by anuejn** [comment]
this should all be implemented now, ready for review :)

**Comment by pajowu** [comment]
Just one small thing:
- Can we rename the "last" button to "done" or similar?

**Comment by anuejn** [comment]
the button is now called "Finish"

**Review by pajowu — APPROVED** [review]

**Pull request merged**
